<?php
    return [
        'Θέλετε να στέλνετε λουλούδια εύκολα, γρήγορα και χωρίς περιορισμούς αποστάσεων; Η eBloom είναι εδώ γι’ αυτόν ακριβώς το λόγο! Πρόκειται για μια νέα ιδέα σχετικά με τον τρόπο που στέλνετε και λαμβάνετε άνθη. Παρατηρώντας μια έλλειψη στις επιλογές αποστολής λουλουδιών στην Ελλάδα δημιουργήσαμε την eBloom, μέσω της οποίας η διαδικασία γίνεται απλά με μερικά click!'=>'Do you want to send flowers easily, quickly and without distance restrictions? eBloom is here for that very reason! It is a new idea on how you send and receive flowers. After noticing a lack of flower delivery options in Greece we created eBloom, through which the process is done with just a few clicks!',
        'Πιστεύουμε πως για κάθε συναίσθημα υπάρχει κι ένα άνθος… Μια τόσο όμορφη κίνηση όσο η προσφορά λουλουδιών μπορεί να αλλάξει άμεσα τη διάθεση του παραλήπτη, να μηδενίσει τις αποστάσεις και να χαρίσει απλόχερα χαμόγελα!Είτε πρόκειται για την ημέρα του Αγίου Βαλεντίνου, μια γιορτή, επέτειο, είτε απλά για να δείξετε στους αγαπημένους σας ανθρώπους πόσο πολύ τους σκέφτεστε, στην eBloom θα βρείτε την κατάλληλη επιλογή για κάθε περίσταση! Υπάρχει ένα τεράστιο δίκτυο συνεργαζόμενων ανθοπωλείων από όπου μπορείτε να παραγγείλετε και να στείλετε λουλούδια κάθε είδους, συνθέσεις ή φυτά μέσα σε δύο ώρες, από όπου κι αν βρίσκεστε, ακόμη και από το εξωτερικό.'=>"We believe that for every emotion there is a flower... A gesture as beautiful as offering flowers can instantly change the recipient's mood, zero the distances and generously grant smiles! Whether it's Valentine's Day, a holiday, an anniversary, or just to show your loved ones how much you appreciate them, at eBloom you will find the right choice for every occasion! There is a huge network of partner flowershops from where you can order and send flowers of any kind, arrangements or plants within two hours, from wherever you are, even from abroad.",
        'Η διαδικασία είναι γρήγορη, εύκολη και – το σημαντικότερο – ασφαλής. Το μόνο που έχετε να κάνετε είναι να γράψετε τη διεύθυνση στην οποία θέλετε να γίνει η παράδοση, να κάνετε την επιλογή σας από τα κοντινά συνεργαζόμενα ανθοπωλεία και να ολοκληρώσετε την πληρωμή με ασφάλεια εντός της πλατφόρμας eBloom.'=>'The process is quick, easy and – most importantly – safe. All you have to do is type in the address where you want the delivery to be made, make your selection from the nearby partner flowershops and complete the payment securely within the eBloom platform.',
        'Στόχος μας είναι να αναβιώσουμε τον ρομαντισμό που πολλές φορές χάνεται στο παρασκήνιο λόγω της καθημερινότητας και των πολλών υποχρεώσεων... Απλοποιώντας λοιπόν την διαδικασία αποστολής λουλουδιών, όσο πιεσμένο κι αν είναι το πρόγραμμά σας, μπορείτε να κάνετε αυτή την όμορφη χειρονομία πανεύκολα και πολύ γρήγορα!'=>'Our goal is to revive the romance that often fades into the background due to everyday life and too many obligations... Therefore, by simplifying the process of sending flowers, no matter how tight your schedule is, you can make this beautiful gesture easily and very quickly!',
        
    ];

?>