<?php
    return [
        'Τα cookies είναι μικρά αρχεία κειμένου που αποστέλλονται στη συσκευή σας όταν επισκέπτεστε μια ιστοσελίδα. Στη συνέχεια τα cookies αποστέλλονται στην ιστοσελίδα προέλευσης σε κάθε επόμενη επίσκεψη ή σε κάποια άλλη ιστοσελίδα που αναγνωρίζει αυτό το cookie. Τα cookies λειτουργούν ως μνήμη σε μια ιστοσελίδα, επιτρέποντας στη συγκεκριμένη ιστοσελίδα να θυμάται τη συσκευή σας κατά τις επόμενες επισκέψεις σας. Τα cookies μπορούν επίσης να θυμούνται τις προτιμήσεις σας, να βελτιώσουν την εμπειρία σας ως χρήστης, καθώς και να προσαρμόζουν τις διαφημίσεις που βλέπετε ανάλογα με αυτά που σας ενδιαφέρουν.' => 'Cookies are small text files that are sent to your device when you visit a website. The cookies are then sent to the originating website on each subsequent visit or to another website that recognizes this cookie. Cookies act as a memory on a website, allowing that website to remember your device on your next visits. Cookies can also remember your preferences, improve your user experience, as well as tailor the ads you see based on what you are interested in.',
        'Για περισσότερες πληροφορίες σχετικά με τα cookies, συμπεριλαμβανομένου του τρόπου που μπορείτε να δείτε τα cookies που έχουν οριστεί στη συσκευή σας και του τρόπου διαχείρισης και διαγραφής τους επισκεφθείτε την ιστοσελίδα www.aboutcookies.org.' => 'For additional information about cookies, including how to view the cookies set on your device and how to manage and delete them, please visit the www.aboutcookies.org website.',
        'Είδη Cookies' => 'Types of Cookies',
        'Προσωρινά και μόνιμα Cookies' => 'Temporary and Persistent Cookies',
        'Ενδέχεται να χρησιμοποιούμε προσωρινά, τα οποία υπάρχουν μέχρι να κλείσετε τον φυλλομετρητή σας. Ενδέχεται να χρησιμοποιούμε μόνιμα cookies, τα οποία διατηρούνται για μεγαλύτερο συγκεκριμένο χρονικό διάστημα.' => 'We may use temporary cookies, which exist until you close your browser. We may use persistent cookies, which are kept for a longer specified period of time.',
        'Cookies τρίτων μερών' => 'Third party cookies',
        'Η ιστοσελίδα μας ενδέχεται να επιτρέπει την εγκατάσταση cookies  τρίτων μερών που εμφανίζονται στην ιστοσελίδα μας. Αυτά τα cookies τρίτων δεν είναι υπό τον έλεγχό μας. Για περαιτέρω πληροφορίες σχετικά με τη χρήση τους, μπορείτε να επισκεφθείτε τη σχετική ιστοσελίδα του τρίτου μέρους για περαιτέρω πληροφορίες. Λεπτομέρειες σχετικά με ενδεχόμενα cookies τρίτων μερών παρουσιάζονται στον πίνακα κατωτέρω.' => 'Our website may allow the installation of cookies from third parties that appear on our website. These third party cookies are not within our control. For further information on their use, you can visit the relevant third party website for further information. Details of potential third party cookies are presented in the table below.',
        'Cookies που χρησιμοποιούνται σε αυτή την ιστοσελίδα' => 'Cookies used on this website',
        'Παρακάτω παρατίθεται περίληψη των cookies που χρησιμοποιούνται στην ιστοσελίδα μας.' => 'Below you will find a summary of the cookies used on our website.',
        'Όνομα Cookie' => 'Cookie name ',
        'Σκοπός' => 'Purpose ',
        'Λήξη' => 'Expiration',
        'Μπορείτε να ρυθμίσετε το πρόγραμμα περιήγησής σας με τέτοιο τρόπο, ώστε να ενημερώνεστε για τη ρύθμιση των cookies και μπορείτε είτε να αποφασίσετε μεμονωμένα για την αποδοχή τους ή συνολικά,  είτε να αποκλείσετε την αποδοχή των cookies σε ορισμένες περιπτώσεις. Κάθε πρόγραμμα περιήγησης διαφέρει ανάλογα με τον τρόπο που διαχειρίζεται τις ρυθμίσεις των cookies. Αυτό περιγράφεται στο μενού βοήθειας κάθε προγράμματος περιήγησης, το οποίο εξηγεί πώς μπορείτε να αλλάξετε τις ρυθμίσεις των cookies. Ακολουθήστε τους παρακάτω συνδέσμους ανάλογα με το πρόγραμμα περιήγησης που χρησιμοποιείτε:' => "You can set your browser in such a way that you are informed about the cookie setting and you can either decide to accept cookies individually or in total, or block the acceptance of cookies in certain cases. Each browser differs depending on how it manages its cookie settings. This is described in each browser's help menu, which explains how you can change the cookie settings. Follow the links below depending on the browser you are using:",
        'Λάβετε υπόψη ότι η λειτουργία της ιστοσελίδας μας ενδέχεται να είναι περιορισμένη εάν τα cookies δεν γίνονται δεκτά.' => 'Please bear in mind that the functionality of our website may be limited if the cookies are not accepted.',
        '' => '',
    ]


?>